import type { Metadata } from "next";
import { Instrument_Sans } from "next/font/google"
import "./globals.css";
import { Toaster } from "react-hot-toast";

const font = Instrument_Sans({
  display: "swap",
  subsets: ["latin", "latin-ext"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.className} antialiased`}
      >
        <Toaster />
        {children}
      </body>
    </html>
  );
}
